CREATE TABLE appointments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL,
    doctor_id UUID NOT NULL,
    clinic_id UUID NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    duration INTEGER NOT NULL DEFAULT 30,
    appointment_type VARCHAR(50) NOT NULL DEFAULT 'consultation',
    status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
    reason TEXT NOT NULL,
    symptoms TEXT,
    notes TEXT,
    diagnosis TEXT,
    treatment_plan TEXT,
    reminder_sent BOOLEAN NOT NULL DEFAULT false,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    cancellation_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('Asia/Singapore',
    NOW()),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('Asia/Singapore',
    NOW()),
    created_by UUID NOT NULL
);