CREATE TABLE patients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    nric VARCHAR(9) UNIQUE NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(10) NOT NULL,
    address TEXT NOT NULL,
    postal_code VARCHAR(6),
    emergency_contact JSONB NOT NULL DEFAULT '{}'::jsonb,
    blood_type VARCHAR(5),
    allergies TEXT[] DEFAULT '{}',
    chronic_conditions TEXT[] DEFAULT '{}',
    current_medications TEXT[] DEFAULT '{}',
    insurance_provider VARCHAR(255),
    insurance_number VARCHAR(100),
    chas_card_number VARCHAR(50),
    chas_card_type VARCHAR(20),
    preferred_language VARCHAR(50) DEFAULT 'English',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('Asia/Singapore',
    NOW()),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('Asia/Singapore',
    NOW()),
    created_by UUID NOT NULL
);