CREATE TABLE payments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL,
    appointment_id UUID,
    amount DECIMAL(10,
    2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'SGD',
    payment_method VARCHAR(20) NOT NULL,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    payment_date TIMESTAMP WITH TIME ZONE,
    transaction_id VARCHAR(255),
    invoice_number VARCHAR(100) UNIQUE,
    description TEXT,
    chas_subsidy DECIMAL(10,
    2) DEFAULT 0.00,
    insurance_claim DECIMAL(10,
    2) DEFAULT 0.00,
    patient_paid DECIMAL(10,
    2) NOT NULL,
    receipt_url TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('Asia/Singapore',
    NOW()),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMEZONE('Asia/Singapore',
    NOW()),
    created_by UUID NOT NULL
);